src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Repository\TrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\MaxDepth;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TrickRepository::class)]
#[UniqueEntity(
    fields: ['name'],
    message: 'Ce trick existe déjà.')
]
class Trick
{
    use EntityIdManagementTrait;

    #[ORM\Column(
        type: 'string',
        length: 128,
        unique: true
    )]
    #[Groups(['paginate_trick'])]
    #[Assert\Regex(
        pattern: '/^[\'"_\-)(.,@\s\wÜ-ü]{2,128}$/',
        message: "Le nom du tricks n'est pas valide. ( entre 2 et 128 lettres, chiffres, espaces et @'\"-_/,(). )"
    )]
    #[Assert\NotBlank()]
    private string $name = '';

    #[ORM\Column(type: 'text')]
    #[Assert\Length(
        min: 2,
        max: 2500,
        minMessage: "Minimum 2 caractères.",
        maxMessage: "Maximum 2500 caractères."
    )]
    #[Assert\Regex(
        pattern: '/[<>&]/',
        message: "Les caractères \"<, > et &\" sont interdits.",
        match: false
    )]
    #[Assert\NotBlank()]
    private string $description = '';

    #[ORM\Column(type: 'datetime')]
    private \DateTimeInterface $creationDate;

    #[ORM\Column(
        type: 'datetime',
        nullable: true
    )]
    private ?\DateTimeInterface $editDate;

    #[ORM\ManyToOne(
        targetEntity: User::class,
        inversedBy: "tricks"
    )]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['paginate_trick'])]
    #[MaxDepth(1)]
    private ?User $author;

    #[ORM\OneToMany(
        mappedBy: "trick",
        targetEntity: Message::class,
        cascade: ["persist", "remove"],
        orphanRemoval: true
    )]
    private Collection $messages;

    #[ORM\ManyToMany(
        targetEntity: Category::class,
        inversedBy: "tricks"
    )]
    private Collection $categories;

    #[ORM\OneToMany(
        mappedBy: "trick",
        targetEntity: Image::class,
        cascade: ["persist", "remove"],
        orphanRemoval: true
    )]
    private Collection $images;

    #[ORM\OneToMany(
        mappedBy: "trick",
        targetEntity: Video::class,
        cascade: ["persist", "remove"],
        orphanRemoval: true
    )]
    private Collection $videos;

    #[ORM\OneToOne(targetEntity: Image::class)]
    #[ORM\JoinColumn(onDelete: "SET NULL")]
    private ?Image $hero = null;

    #[ORM\Column(type: "string", length: 255, unique: true)]
    #[Groups(['paginate_trick'])]
    private ?string $slug = null;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
        $this->categories = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->creationDate = new \DateTime();
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creationDate;
    }

    public function setCreationDate(\DateTimeInterface $creationDate): self
    {
        $this->creationDate = $creationDate;

        return $this;
    }

    public function getEditDate(): ?\DateTimeInterface
    {
        return $this->editDate;
    }

    public function setEditDate(?\DateTimeInterface $editDate): self
    {
        $this->editDate = $editDate;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages($maxResults = null, $firstResult = null): Collection
    {
        $criteria = Criteria::create()
            ->orderBy(['date' => Criteria::DESC])
            ->setMaxResults($maxResults)
            ->setFirstResult($firstResult)
        ;
        return $this->messages->matching($criteria);
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setTrick($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getTrick() === $this) {
                $message->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addTrick($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->removeElement($category)) {
            $category->removeTrick($this);
        }

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setTrick($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getTrick() === $this) {
                $image->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Video[]
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }

    public function getHero(): ?Image
    {
        return $this->hero;
    }

    public function setHero(?Image $hero): self
    {
        if ($hero->getTrick() === $this) {
            $this->hero = $hero;
        }

        return $this;
    }

    #[Groups(['paginate_trick'])]
    public function getHeroUrl(): string
    {
        if ($this->getHero()) {
            return "uploads/tricks/" . $this->getHero()->getName();
        }
        if (!$this->getImages()->isEmpty()) {
            return "uploads/tricks/" . $this->getImages()->first()->getName();
        }
        return "imgs/no-image.png";
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function computeSlug(SluggerInterface $slugger, TrickRepository $trickRepository)
    {
        $slug = (string) $slugger->slug((string) $this->getName())->lower();
        $matchedTrick = $trickRepository->findOneBy(['slug' => $slug]);
        if ($matchedTrick && $matchedTrick !== $this && $this->slug !== $slug) {
            $key = 2;
            $matchedTrick = $trickRepository->findOneBy(['slug' => $slug . "_" . $key]);
            while ($matchedTrick && $matchedTrick !== $this) {
                $key++;
                $matchedTrick = $trickRepository->findOneBy(['slug' => $slug . "_" . $key]);
            }
            $slug .= "_" . $key;
        }
        $this->slug = $slug;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use DateTimeInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: "user")]
class User implements PasswordAuthenticatedUserInterface, UserInterface
{
    use EntityIdManagementTrait;

    #[ORM\Column(type: "string", length: 180, unique: true)]
    #[Assert\Email(message: "Ton adresse Email est invalide.")]
    #[Groups(['paginate_user'])]
    private string $email;

    #[ORM\Column(type: "json")]
    #[Groups(['paginate_user', 'paginate_trick'])]
    private array $roles = [];

    #[ORM\Column(type: "string")]
    private string $password;

    #[ORM\Column(type: "string", length: 128, unique: true)]
    #[Groups(['paginate_message', 'paginate_user'])]
    #[Assert\Length(
        min: 2,
        max: 128,
        minMessage: "Minimum 2 caractères.",
        maxMessage: "Maximum 128 caractères."
    )]
    #[Assert\Regex(
        pattern: '/[<>&]/',
        message: "Les caractères \"<, > et &\" sont interdits!!!!.",
        match: false
    )]
    private string $username;

    #[ORM\Column(type: "datetime")]
    #[Groups(['paginate_user'])]
    private DateTimeInterface $subscriptionDate;

    #[ORM\Column(type: "boolean")]
    #[Groups(['paginate_user'])]
    private bool $enabled = false;

    #[ORM\OneToMany(
        mappedBy: "author",
        targetEntity: Trick::class,
        cascade: ["persist", "remove"],
        orphanRemoval: true
    )]
    private Collection $tricks;

    #[ORM\OneToMany(
        mappedBy: "author",
        targetEntity: Message::class,
        cascade: ["persist", "remove"],
        orphanRemoval: true
    )]
    private Collection $messages;

    #[ORM\OneToOne(
        mappedBy: "user",
        targetEntity: Token::class,
        cascade: ["persist", "remove"],
        orphanRemoval: true
    )]
    private ?Token $token;

    #[ORM\Column(
        type: "string",
        length: 32,
        nullable: true
    )]
    private ?string $avatar;

    public function __construct()
    {
        $this->tricks = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getUsername(): string
    {
        return $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getSubscriptionDate(): ?DateTimeInterface
    {
        return $this->subscriptionDate;
    }

    public function setSubscriptionDate(DateTimeInterface $subscriptionDate): self
    {
        $this->subscriptionDate = $subscriptionDate;

        return $this;
    }

    public function getEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    public function getToken(): ?Token
    {
        return $this->token;
    }

    public function setToken(Token $token): self
    {
        $this->token = $token;

        return $this;
    }

    /**
     * @return Collection|Trick[]
     */
    public function getTricks(): Collection
    {
        return $this->tricks;
    }

    public function addTrick(Trick $trick): self
    {
        if (!$this->tricks->contains($trick)) {
            $this->tricks[] = $trick;
            $trick->setAuthor($this);
        }

        return $this;
    }

    public function removeTrick(Trick $trick): self
    {
        if ($this->tricks->removeElement($trick)) {
            // set the owning side to null (unless already changed)
            if ($trick->getAuthor() === $this) {
                $trick->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setAuthor($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getAuthor() === $this) {
                $message->setAuthor(null);
            }
        }

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    #[Groups(['paginate_message'])]
    public function getAvatarUrl(): string
    {
        if ($this->avatar) {
            return '/uploads/avatars/' . $this->avatar;
        }
        return "/imgs/avatar.png";
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function switchRole(): self
    {
        if (in_array('ROLE_ADMIN',$this->getRoles())) {
            $this->setRoles(['ROLE_USER']);
            return $this;
        }
        $this->setRoles(['ROLE_ADMIN']);
        return $this;
    }
}

templates/front/_front-base.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <!-- Frontend CSS -->
    <link rel="stylesheet" href="{{ asset("css/style-front.css") }}" type="text/css" />
{% endblock %}

{% block header %}
    <header style="position: relative" id="top">
        <div id="NavContainer">

            {% include 'front/_front-nav.html.twig' %}

            <div id="flash-messages-container" class="container-fluid fixed fixed-top-sm justify-content-around">
                <div class="row justify-content-around align-items-baseline">
                    {% for label, messages in app.flashes %}
                        {% for message in messages %}
                            <div class="col-auto alert-container">
                                <div class="alert alert-{{ label }} alert-dismissible fade show my-1" role="alert">
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            </div>
                        {% endfor %}
                    {% endfor %}
                </div>
            </div>
        </div>
        {%  block headerHero %}{% endblock %}
    </header>

    {% if not app.user %}
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginModalLabel">Se connecter</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form name="login" method="post">
                    <div class="modal-body">
                        <div class="errors">
                            {% if error %}
                                <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                            {% endif %}
                        </div>

                        <label for="inputEmail">Email</label>
                        <input type="email" value="{{ last_username }}" name="login[email]" id="inputEmail" class="form-control" required autofocus>
                        <label for="inputPassword" class="mt-3">Mot de passe</label>
                        <input type="password" name="login[password]" id="inputPassword" class="form-control" required>

                        <input type="hidden" name="login[_csrf_token]" value="{{ csrf_token('authenticate') }}">

                        <div class="row text-center mt-4">
                            <div class="col-12 col-md-5"><a href="{{ path('security_registration') }}">S'inscrire</a></div>
                            <div class="col-2 d-none d-md-block"></div>
                            <div class="col-12 col-md-5"><a href="{{ path('security_password_forgot') }}">Mot de passe oublié</a></div>
                        </div>

                        {#
                            Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
                            See https://symfony.com/doc/current/security/remember_me.html

                            <div class="checkbox mb-3">
                                <label>
                                    <input type="checkbox" name="_remember_me"> Remember me
                                </label>
                            </div>
                        #}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>

                        <button class="btn btn-primary" type="submit">
                            Se connecter
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

{% block javascriptsBottom %}
    {{ parent() }}
    <script src="{{ asset('js/frontend.js') }}"></script>
    <script src="{{ asset('js/flash-alerts.js') }}"></script>
{% endblock %}

templates/front/_front-nav.html.twig
<nav class="navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ path('front_home') }}#"><h1 class="d-none d-sm-block logo">SnowTricks</h1></a>
    <div class="collapse navbar-collapse" id="frontNavbar">
        <ul class="nav navbar-nav ml-sm-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% if app.request.attributes.get('_route') != 'front_home' %}{{ path('front_home') }}{% endif %}#top">
                    <span class="d-none d-sm-inline">Accueil<span class="sr-only">(current)</span></span>
                    <em class="fas fa-home d-sm-none"></em>
                </a>
            </li>
            <li class="nav-item{% if app.request.attributes.get('_route') matches '/^front_tricks-/' %} active{% endif %}">
                <a class="nav-link" href="{% if app.request.attributes.get('_route') != 'front_home' %}{{ path('front_home') }}{% endif %}#tricksList" title="Tricks">
                    <span class="d-none d-sm-inline">Tricks</span>
                    <em class="icon trick-icon d-sm-none"></em>
                </a>
            </li>
            {% if app.user %}
            <li class="nav-item dropdown user-tools">
                <a class="nav-link dropdown-toggle" href="#" id="navbarUserDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" title="Tes outils">
                    <img src="{{ app.user.avatarUrl }}" class="rounded-circle border border-info" alt="Avatar">
                </a>
                <div class="dropdown-menu bg-dark" aria-labelledby="navbarUserDropdown">
                    <div class="text-center profile-info"><span class="text-warning">{{ app.user.username }}</span></div>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ path('profile_edit') }}">Profil</a>
                    {% if is_granted('ROLE_ADMIN') %}<a class="dropdown-item" href="{{ path('admin_users') }}">Administration</a>{% endif %}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ path('security_logout') }}">Déconnexion</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal" title="Connexion / Inscription">
                    <span class="d-none d-sm-inline">Connexion</span>
                    <em class="fas fa-sign-in-alt d-sm-none"></em>
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/front/home.html.twig
{% extends 'front/_front-base.html.twig' %}

{%  block headerHero %}
    <div id="homeHero">
        <div class="top-ref">&nbsp;</div>
        <a class="brand" href="{{ path('front_home') }}#"><h1 class="d-sm-none logo">SnowTricks</h1></a>
        <h2>La référence communautaire des Tricks de SnowBoard</h2>
        <div class="hero-bottom"><a class="down-arrow" href="#tricksList" title="Tricks"><em class="fas fa-arrow-down"></em></a></div>
    </div>
{% endblock %}

{% block content %}
    <section class="container-fluid tricks-list pb-3" id="tricksList">
        {% if app.user %}
        <div class="row">
            <div class="col-12 text-center mt-2">
                <a class="btn btn-info" href="{{ path('front_tricks-add') }}" title="Ajouter un trick">Ajouter un Trick</a>
            </div>
        </div>
        {% endif %}

        <div class="row row-cols-1 row-cols-md-3 row-cols-xl-5 justify-content-around pt-2 pt-xl-3 items">
            {% for trick in tricks %}
                {% include 'front/trick-item.html.twig' %}
            {% endfor %}
        </div>

        {% if app.user %}
            <div class="row">
                <div class="col-12 text-center mb-2">
                    <a class="btn btn-info" href="{{ path('front_tricks-add') }}" title="Ajouter un trick">Ajouter un Trick</a>
                </div>
            </div>
        {% endif %}
        <div class="row my-2">
            <div class="col-12 text-center">
                {% if paginate_tricks %}
                    <button class="btn btn-primary pagination-btn" data-target="#tricksList>div.items" data-entity="trick">Voir plus</button>
                {% endif %}
                <div class="trick-up"><a class="up-arrow" href="#tricksList" title="Premiers Tricks"><em class="fas fa-arrow-up"></em></a></div>
            </div>
        </div>

    </section>

    <div class="modal fade" id="trickDeleteModal" tabindex="-1" role="dialog" aria-labelledby="trickDeleteModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="trickDeleteModalTitle">Supprimer le Trick</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="errors">
                        <div class="alert alert-warning">Es tu sûr de vouloir supprimer le Trick "<span class="trick-name"></span>" ?</div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                    <button type="button" class="btn btn-danger delete-btn" data-token="{{ csrf_token('delete-trick') }}">Supprimer</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascriptsBottom %}
    {{ parent() }}
    <script>
        const currentUser = {% if app.user %}{{ app.user.id }}{% else %}null{% endif %}
    </script>
    <script src="{{ asset('js/home.js') }}"></script>
    <script src="{{ asset('js/pagination.js') }}"></script>
{% endblock %}

templates/front/message-item.html.twig
<div class="row px-1 justify-content-center message-item trick-message-{{ message.id }}">
    <div class="col-2 col-md-1 text-center mt-4 pr-0 text-wrap message-author">
        <img src="{{ message.author.avatarUrl }}" class="img-fluid rounded-circle border border-info d-block m-auto w-100" alt="Avatar">
        <small class="text-break">{{ message.author.username }}</small>
    </div>
    <div class="col-10 col-md-11 col-xl-6 mt-3 message-content">
        <div class="border rounded px-2">
            <p class="mb-2 border-bottom"><small class="text-muted"><strong>Le {{ message.date|date('d/m/Y à H:m:s') }}</strong></small></p>
            <p>{{ message.content|nl2br() }}</p>
            {% if is_granted('ROLE_ADMIN') or message.author == app.user %}
            <div class="text-right delete-message-btn-container">
                <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#messageDeleteModal" data-id="{{ message.id }}">Supprimer</button>
            </div>
            {% endif %}
        </div>
    </div>
</div>

templates/front/trick-item.html.twig
<article class="col mb-3 mb-md-4 trick-item trick-{{ trick.id }}">
    <div class="card h-100">
        <div class="item-header">
            <a href="{{ path('front_tricks-single', {slug : trick.slug}) }}" title="Voir le trick">
                <img src="{{ trick.heroUrl }}" class="card-img-top" alt="{{ trick.name }}">
            </a>
        </div>
        <div class="card-body">
            <h3 class="card-title mb-0">
                <a href="{{ path('front_tricks-single', {slug : trick.slug}) }}" title="Voir le trick">{{ trick.name }}</a>
            </h3>
        </div>

        {% if is_granted('ROLE_ADMIN') or app.user == trick.author %}
        <div class="card-footer">
            <div class="row">
                <div class="col-6 text-center edit">
                    <a href="{{ path('front_tricks-edit', {slug: trick.slug}) }}" title="Modifier le Trick" class="edit-btn"><em class="far fa-edit"></em></a>
                </div>
                <div class="col-6 text-center delete">
                    <a href="#" title="Supprimer les Trick" class="delete-btn" data-toggle="modal" data-target="#trickDeleteModal" data-name="{{ trick.name }}" data-id="{{ trick.id }}"><em class="far fa-trash-alt"></em></a>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</article>